### ISSUE TITLE
Named export 'AccordionItem' not found.

### ISSUE THREAD

**Issue by dmitrisi4** [sticker0ne/vue3-rich-accordion#4]
When I try to deploy ssr project(InertiaJS Vue3) I get this error

`import { AccordionList, AccordionItem, useAccordion } from "vue3-rich-accordion";
                        ^^^^^^^^^^^^^
SyntaxError: Named export 'AccordionItem' not found. The requested module 'vue3-rich-accordion' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue3-rich-accordion';
const { AccordionList, AccordionItem, useAccordion } = pkg;`

**Comment by sticker0ne** [comment]
Hi, @dmitrisi4 
It is not an issue of plugin. Sounds like problem with configs of your app.

I think you have different config for prod and dev modes. (maybe webpack and vite)
Plugin's folder dist contains both accordion-library.es.js and accordion-library.umd.js files for different variants of an import.

I think, you have [same issuie](https://laracasts.com/discuss/channels/inertia/problema-with-inertiajs-ssr-vite)
